export enum Icons {
  Airport = 'airport',
  Applause = 'applause',
  Birdsong = 'birdsong',
  Car = 'car',
  Clock = 'clock',
  Cityscape = 'cityscape',
  Electricity = 'electricity',
  Forest = 'forest',
  GentleRain = 'gentle_rain',
  Guitar = 'guitar',
  Keyboard = 'keyboard',
  LofiHipHop = 'lofi_hip_hop',
  Piano = 'piano',
  RainOnMetal = 'rooftop_rain',
  RainOnWindow = 'rain_on_window',
  Sea = 'sea',
  Thunder = 'thunder',
  Thunderstorm = 'thunderstorm',
  Violin = 'violin',
  Volcano = 'volcano',
  Whisper = 'whisper',
  Whistle = 'whistle',
  Wind = 'wind',
  Wolf = 'wolf'
}
